# Generated by Django 4.2.15 on 2026-04-25 23:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_articlemodel_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='artlistmodel',
            name='bodyref',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.articlemodel'),
            preserve_default=False,
        ),
    ]
