# Generated by Django 4.2.15 on 2026-04-25 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_artlistmodel_bodyref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artlistmodel',
            old_name='subtitle',
            new_name='image',
        ),
    ]
