# Generated by Django 4.2.15 on 2026-04-25 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LevelsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('type', models.IntegerField(default=0)),
                ('images', models.JSONField(blank=True, default=dict, null=True)),
                ('answers', models.JSONField(blank=True, default=dict, null=True)),
                ('answer', models.CharField(blank=True, max_length=1000)),
                ('answernumber', models.IntegerField(blank=True, null=True)),
                ('hint', models.CharField(blank=True, max_length=1000)),
                ('solution', models.IntegerField(default=0)),
                ('aftertext', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ProphecyLessonsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('part', models.IntegerField(default=0)),
                ('videourl', models.CharField(max_length=1000)),
                ('sources', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='QuotesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Bible', 'ΑΓΙΑ ΓΡΑΦΗ'), ('Cons', 'ΣΥΝΩΜΟΣΙΑ'), ('Mov-Ser', 'ΤΑΙΝΙΕΣ/ΣΕΙΡΕΣ')], max_length=1000)),
                ('author', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=10000)),
                ('source', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ShortsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.CharField(max_length=1000)),
                ('category', models.CharField(choices=[('15MINCITIES', 'ΠΟΛΕΙΣ 15 ΛΕΠΤΩΝ'), ('SYNAGOGUEANDANTICHRIST', 'ΣΥΝΑΓΩΓΗ ΤΟΥ ΣΑΤΑΝΑ ΚΑΙ Ο ΑΝΤΙΧΡΙΣΤΟΣ'), ('CHIPS', 'ΤΣΙΠΑΚΙΑ'), ('CONTROL', 'ΕΛΕΓΧΟΣ'), ('Covid', 'ΚΟΡΩΝΟΪΟΣ'), ('COVIDPROGRAMMING', 'ΚΟΡΩΝΟΪΟΣ ΠΡΟΓΝΩΣΤΙΚΟΣ ΠΡΟΓΡΑΜΜΑΤΙΣΜΟΣ'), ('ELITESRELIGION', "Η ΠΡΑΓΜΑΤΙΚΗ ΘΡΗΣΚΕΙΑ ΤΩΝ 'ΠΕΤΥΧΗΜΕΝΩΝ'"), ('FAKEALIENINVATION', 'ΨΕΥΤΙΚΗ ΕΞΩΓΗΙΝΗ ΕΙΣΒΟΛΗ'), ('OVERPOPULATION', 'ΜΕΙΩΣΗ ΤΟΥ ΠΛΗΘΥΣΜΟΥ'), ('EXTRA', 'ΕΠΙΠΛΕΟΝ'), ('NOSOURCE', 'ΧΩΡΙΣ ΠΗΓΗ')], max_length=1000)),
                ('link', models.CharField(max_length=1000)),
                ('source', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UnlearnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videourl', models.CharField(max_length=1000)),
                ('sources', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='VideosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('thumbnail', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=1000)),
                ('sources', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='NotificationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('type', models.IntegerField()),
                ('quotesource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.quotesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LevelsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=1000)),
                ('image', models.CharField(default='', max_length=1000)),
                ('groups', models.ManyToManyField(to='pages.levelsmodel')),
            ],
        ),
    ]
