# Generated by Django 4.2.15 on 2026-08-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=10000)),
                ('source', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('store', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=10000)),
                ('source', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('alternatives', models.CharField(max_length=1000)),
                ('importance', models.CharField(choices=[('MUSTHAVE', 'MUSTHAVE'), ('SECONDARY', 'SECONDARY'), ('THIRD', 'THIRD')], max_length=1000)),
                ('category', models.CharField(choices=[('Αποθηκευτικός χώρος', 'Αποθηκευτικός χώρος'), ('Νερό', 'Νερό'), ('Εργαλεία', 'Εργαλεία'), ('Καταφύγιο', 'Καταφύγιο'), ('Φωτιά', 'Φωτιά'), ('Ηλεκτρονικά', 'Ηλεκτρονικά'), ('Ύπνος', 'Ύπνος'), ('Ενδυμασία', 'Ενδυμασία'), ('Ψάρεμα', 'Ψάρεμα'), ('Καθημερινότητα', 'Καθημερινότητα')], max_length=1000)),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
    ]
