# Generated by Django 4.2.15 on 2026-08-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_bookmodel_itemmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videourl', models.CharField(max_length=1000)),
                ('sources', models.JSONField()),
            ],
        ),
    ]
